spring.application.name=Back
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/game_storage
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# Configuración para Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b0e9dc97299325
spring.mail.password=0b9b241370ce41
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

