spring.application.name=Back
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/game_storage
spring.datasource.password=Reach432K
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

