spring.application.name=Back
rawg.api.key=96a643aeafdb4c5385c89819aa4e03a2
spring.datasource.username=postgres
spring.datasource.password=Reach432K
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresPlusDialect