BEGIN;

-- TABLAS PRINCIPALES

CREATE TABLE IF NOT EXISTS bundle (
    id_bundle bigint PRIMARY KEY,
    imagen_url text,
    nombre varchar(255)
);


CREATE TABLE IF NOT EXISTS bundle_productos (
    steam_app_id bigint PRIMARY KEY,
    descripcion text,
    imagen_url text,
    nombre varchar(255),
    bundle bigint,
    CONSTRAINT fk_bundle_productos_bundle
        FOREIGN KEY (bundle)
        REFERENCES public.bundle(id_bundle)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS tienda (
    id_tienda BIGINT PRIMARY KEY,
    banner TEXT,
    icon TEXT,
    logo TEXT,
    nombre VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS genero (
    id_genre BIGINT PRIMARY KEY,
    descripcion VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario UUID PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    recibir_notificaciones BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS videojuego (
    id_videojuego BIGINT PRIMARY KEY,
    acerca_de TEXT,
    desarolladores VARCHAR(255),
    descripcion TEXT,
    descripcion_corta TEXT,
    distribuidora VARCHAR(255),
    fecha_lanzamiento DATE,
    imagen_url TEXT,
    imagen_url_resolucion_baja TEXT,
    nombre VARCHAR(255),
    steam_rating_percent INTEGER,
    steam_rating_text VARCHAR(255)
);

-- TABLAS RELACIONALES

CREATE TABLE IF NOT EXISTS captura (
    id_captura BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagen TEXT UNIQUE,
    miniatura TEXT,
    videojuego BIGINT,

    CONSTRAINT fk_captura_videojuego
        FOREIGN KEY (videojuego)
        REFERENCES public.videojuego(id_videojuego)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS movie (
    id_movie BIGINT PRIMARY KEY,
    miniatura TEXT,
    titulo TEXT,
    video TEXT,
    videojuego BIGINT,

    CONSTRAINT fk_movie_videojuego
        FOREIGN KEY (videojuego)
        REFERENCES public.videojuego(id_videojuego)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS genero_videojuego (
    id_videojuego BIGINT NOT NULL,
    id_genre BIGINT NOT NULL,

    PRIMARY KEY (id_videojuego, id_genre),

    CONSTRAINT fk_genero_videojuego_videojuego
        FOREIGN KEY (id_videojuego)
        REFERENCES public.videojuego(id_videojuego)
        ON DELETE CASCADE,

    CONSTRAINT fk_genero_videojuego_genero
        FOREIGN KEY (id_genre)
        REFERENCES public.genero(id_genre)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bundle_productos_capturas (
    bundle_productos_steam_app_id bigint NOT NULL,
    imagen varchar(255),
    miniatura varchar(255),
    CONSTRAINT fk_bp_capturas
        FOREIGN KEY (bundle_productos_steam_app_id)
        REFERENCES public.bundle_productos(steam_app_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS bundle_productos_movies (
    bundle_productos_steam_app_id bigint NOT NULL,
    miniatura varchar(255),
    video varchar(255),
    CONSTRAINT fk_bp_movies
        FOREIGN KEY (bundle_productos_steam_app_id)
        REFERENCES public.bundle_productos(steam_app_id)
        ON DELETE CASCADE
);

-- WISHLIST 

CREATE TABLE IF NOT EXISTS wishlist (
    id_wishlist BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fecha_agregado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    user_id UUID NOT NULL UNIQUE,

    CONSTRAINT fk_wishlist_usuario
        FOREIGN KEY (user_id)
        REFERENCES public.usuario(id_usuario)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wishlist_bundles (
    id_wishlist BIGINT NOT NULL,
    id_bundle BIGINT NOT NULL,

    PRIMARY KEY (id_wishlist, id_bundle),

    CONSTRAINT fk_wishlist_bundles_wishlist
        FOREIGN KEY (id_wishlist)
        REFERENCES public.wishlist(id_wishlist)
        ON DELETE CASCADE,

    CONSTRAINT fk_wishlist_bundles_bundle
        FOREIGN KEY (id_bundle)
        REFERENCES public.bundle(id_bundle)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS wishlist_videojuegos (
    id_wishlist BIGINT NOT NULL,
    id_videojuego BIGINT NOT NULL,

    PRIMARY KEY (id_wishlist, id_videojuego),

    CONSTRAINT fk_wishlist_videojuegos_wishlist
        FOREIGN KEY (id_wishlist)
        REFERENCES public.wishlist(id_wishlist)
        ON DELETE CASCADE,

    CONSTRAINT fk_wishlist_videojuegos_videojuego
        FOREIGN KEY (id_videojuego)
        REFERENCES public.videojuego(id_videojuego)
        ON DELETE CASCADE
);

-- OFERTAS

CREATE TABLE IF NOT EXISTS oferta (
    id_oferta VARCHAR(255) PRIMARY KEY,

    ahorro DOUBLE PRECISION,
    cambiar_img BOOLEAN DEFAULT false,

    inicio_oferta TIMESTAMP,

    oferta_rating DOUBLE PRECISION,

    precio_oferta DOUBLE PRECISION NOT NULL,
    precio_original DOUBLE PRECISION NOT NULL,

    steam_appid BIGINT NOT NULL,

    steam_rating INTEGER,

    thumb TEXT,
    titulo VARCHAR(255),

    url_compra TEXT,

    tienda BIGINT,
    videojuego BIGINT,
    bundle BIGINT,

    url_imagen TEXT,

    CONSTRAINT fk_oferta_tienda
        FOREIGN KEY (tienda)
        REFERENCES public.tienda(id_tienda)
        ON DELETE SET NULL,

    CONSTRAINT fk_oferta_videojuego
        FOREIGN KEY (videojuego)
        REFERENCES public.videojuego(id_videojuego)
        ON DELETE CASCADE,

    CONSTRAINT fk_oferta_bundle
        FOREIGN KEY (bundle)
        REFERENCES public.bundle(id_bundle)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS oferta_staging (
    id_oferta VARCHAR(255) PRIMARY KEY,

    ahorro DOUBLE PRECISION,
    cambiar_img BOOLEAN DEFAULT false,

    inicio_oferta TIMESTAMP,

    oferta_rating DOUBLE PRECISION,

    precio_oferta DOUBLE PRECISION NOT NULL,
    precio_original DOUBLE PRECISION NOT NULL,

    steam_appid BIGINT NOT NULL,

    steam_rating INTEGER,

    thumb TEXT,
    titulo VARCHAR(255),

    url_compra TEXT,

    tienda BIGINT,
    videojuego BIGINT,
    bundle BIGINT,

    CONSTRAINT fk_oferta_staging_tienda
        FOREIGN KEY (tienda)
        REFERENCES public.tienda(id_tienda)
        ON DELETE SET NULL,

    CONSTRAINT fk_oferta_staging_videojuego
        FOREIGN KEY (videojuego)
        REFERENCES public.videojuego(id_videojuego)
        ON DELETE CASCADE,

    CONSTRAINT fk_oferta_staging_bundle
        FOREIGN KEY (bundle)
        REFERENCES public.bundle(id_bundle)
        ON DELETE SET NULL
);

-- MATERIALIZED VIEW

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ofertas_unicas AS
WITH cheapest AS (
    SELECT DISTINCT ON (o.steam_appid)
        o.steam_appid,
        o.titulo,
        o.precio_oferta,
        o.ahorro,
        o.oferta_rating,
        o.inicio_oferta AS recent,
        o.steam_rating AS reviews,
        o.thumb AS imagen
    FROM public.oferta o
    ORDER BY
        o.steam_appid,
        o.precio_oferta ASC,
        o.oferta_rating DESC NULLS LAST
),

tiendas AS (
    SELECT
        steam_appid,
        ',' || string_agg(DISTINCT tienda::TEXT, ',') || ',' AS tienda_ids
    FROM public.oferta
    WHERE tienda IS NOT NULL
    GROUP BY steam_appid
)

SELECT
    c.steam_appid,
    c.titulo,
    c.precio_oferta,
    c.ahorro,
    c.oferta_rating,
    c.recent,
    c.reviews,
    c.imagen,
    t.tienda_ids
FROM cheapest c
LEFT JOIN tiendas t USING (steam_appid);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_ofertas_unicas_appid
ON public.mv_ofertas_unicas (steam_appid);

COMMIT;