BEGIN;

-- 1. Tablas base (sin dependencias)
CREATE TABLE IF NOT EXISTS tienda (
    id_tienda bigint NOT NULL PRIMARY KEY,
    banner text,
    icon text,
    logo text,
    nombre varchar(255)
);

CREATE TABLE IF NOT EXISTS genero (
    id_genre bigint NOT NULL PRIMARY KEY,
    descripcion varchar(255)
);

CREATE TABLE IF NOT EXISTS videojuego (
    id_videojuego bigint NOT NULL PRIMARY KEY,
    acerca_de text,
    desarolladores varchar(255),
    descripcion text,
    descripcion_corta text,
    distribuidora varchar(255),
    fecha_lanzamiento date,
    imagen_url text,
    imagen_url_resolucion_baja text,
    nombre varchar(255),
    steam_rating_percent integer NOT NULL,
    steam_rating_text varchar(255)
);

-- 2. Tablas con claves foráneas integradas
CREATE TABLE IF NOT EXISTS captura (
    id_captura bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imagen text UNIQUE,
    miniatura text,
    videojuego bigint REFERENCES videojuego(id_videojuego)
);

CREATE TABLE IF NOT EXISTS genero_videojuego (
    id_videojuego bigint NOT NULL REFERENCES videojuego(id_videojuego),
    id_genre bigint NOT NULL REFERENCES genero(id_genre),
    PRIMARY KEY (id_videojuego, id_genre)
);

CREATE TABLE IF NOT EXISTS movie (
    id_movie bigint NOT NULL PRIMARY KEY,
    miniatura text,
    titulo text,
    video text,
    videojuego bigint REFERENCES videojuego(id_videojuego)
);

CREATE TABLE IF NOT EXISTS oferta (
    id_oferta varchar(255) NOT NULL PRIMARY KEY,
    ahorro double precision NOT NULL,
    inicio_oferta timestamp(6),
    oferta_rating double precision NOT NULL,
    precio_oferta double precision NOT NULL,
    precio_original double precision NOT NULL,
    steam_appid bigint NOT NULL,
    steam_rating integer NOT NULL,
    thumb text,
    titulo varchar(255),
    url_compra text,
    url_imagen text,
    tienda bigint REFERENCES tienda(id_tienda),
    videojuego bigint REFERENCES videojuego(id_videojuego)
);

-- 3. Vistas y otros objetos
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ofertas_unicas AS
WITH cheapest AS (
    SELECT DISTINCT ON (o.steam_appid)
        o.steam_appid,
        o.titulo,
        o.precio_oferta,
        o.ahorro,
        o.oferta_rating,
        o.inicio_oferta AS recent,
        o.steam_rating AS reviews,
        o.thumb AS imagen
    FROM oferta o
    ORDER BY o.steam_appid, o.precio_oferta ASC, o.oferta_rating DESC
),
tiendas AS (
    SELECT 
        steam_appid,
        ',' || string_agg(DISTINCT tienda::text, ',') || ',' AS tienda_ids
    FROM oferta
    GROUP BY steam_appid
)
SELECT 
    c.steam_appid,
    c.titulo,
    c.precio_oferta,
    c.ahorro,
    c.oferta_rating,
    c.recent,
    c.reviews,
    c.imagen,
    t.tienda_ids
FROM cheapest c
JOIN tiendas t USING (steam_appid);

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_ofertas_unicas_appid 
ON mv_ofertas_unicas (steam_appid);


COMMIT;