BEGIN;

-- 1. TABLAS BASE
-------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tienda (
                                      id_tienda bigint NOT NULL PRIMARY KEY,
                                      banner text,
                                      icon text,
                                      logo text,
                                      nombre varchar(255)
    );

CREATE TABLE IF NOT EXISTS genero (
                                      id_genre bigint NOT NULL PRIMARY KEY,
                                      descripcion varchar(255)
    );

CREATE TABLE IF NOT EXISTS bundle (
                                      id_bundle bigint NOT NULL PRIMARY KEY,
                                      imagen_url text,
                                      nombre varchar(255)
    );

CREATE TABLE IF NOT EXISTS usuario (
                                       id_usuario uuid NOT NULL PRIMARY KEY,
                                       email varchar(255) UNIQUE
    );

CREATE TABLE IF NOT EXISTS videojuego (
                                          id_videojuego bigint NOT NULL PRIMARY KEY,
                                          acerca_de text,
                                          desarolladores varchar(255),
    descripcion text,
    descripcion_corta text,
    distribuidora varchar(255),
    fecha_lanzamiento date,
    imagen_url text,
    imagen_url_resolucion_baja text,
    nombre varchar(255),
    steam_rating_percent integer, -- Removido NOT NULL
    steam_rating_text varchar(255)
    );

-- 2. TABLAS RELACIONALES
-------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS captura (
                                       id_captura bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       imagen text UNIQUE,
                                       miniatura text,
                                       videojuego bigint REFERENCES videojuego(id_videojuego) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS movie (
                                     id_movie bigint NOT NULL PRIMARY KEY,
                                     miniatura text,
                                     titulo text,
                                     video text,
                                     videojuego bigint REFERENCES videojuego(id_videojuego) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS genero_videojuego (
                                                 id_videojuego bigint NOT NULL REFERENCES videojuego(id_videojuego) ON DELETE CASCADE,
    id_genre bigint NOT NULL REFERENCES genero(id_genre) ON DELETE CASCADE,
    PRIMARY KEY (id_videojuego, id_genre)
    );

CREATE TABLE IF NOT EXISTS bundles_videojuego (
                                                  id_videojuego bigint NOT NULL REFERENCES videojuego(id_videojuego) ON DELETE CASCADE,
    id_bundle bigint NOT NULL REFERENCES bundle(id_bundle) ON DELETE CASCADE,
    PRIMARY KEY (id_videojuego, id_bundle)
    );

CREATE TABLE IF NOT EXISTS bundle_productos (
                                                id_producto SERIAL PRIMARY KEY,
                                                bundle_id_bundle bigint REFERENCES bundle(id_bundle) ON DELETE CASCADE,
    external_id bigint,
    name varchar(255)
    );

CREATE TABLE IF NOT EXISTS wishlist (
                                        id_wishlist SERIAL PRIMARY KEY,
                                        user_id UUID NOT NULL,
                                        id_videojuego BIGINT NOT NULL REFERENCES videojuego(id_videojuego) ON DELETE CASCADE,
    fecha_agregado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_game UNIQUE (user_id, id_videojuego)
    );

CREATE TABLE IF NOT EXISTS oferta (
                                      id_oferta varchar(255) NOT NULL PRIMARY KEY,
    ahorro double precision, -- Permitir NULL
    inicio_oferta timestamp(6),
    oferta_rating double precision, -- Permitir NULL
    precio_oferta double precision NOT NULL,
    precio_original double precision NOT NULL,
    steam_appid bigint NOT NULL,
    steam_rating integer, -- Permitir NULL
    thumb text,
    titulo varchar(255),
    url_compra text,
    url_imagen text,
    cambiar_img boolean,
    tienda bigint REFERENCES tienda(id_tienda) ON DELETE SET NULL,
    videojuego bigint REFERENCES videojuego(id_videojuego) ON DELETE CASCADE,
    bundle bigint REFERENCES bundle(id_bundle) ON DELETE SET NULL
    );

-- 3. VISTAS MATERIALIZADAS
-------------------------------------------------------------------------

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ofertas_unicas AS
WITH cheapest AS (
    SELECT DISTINCT ON (o.steam_appid)
        o.steam_appid,
        o.titulo,
        o.precio_oferta,
        o.ahorro,
        o.oferta_rating,
        o.inicio_oferta AS recent,
        o.steam_rating AS reviews,
        o.thumb AS imagen
    FROM oferta o
    ORDER BY o.steam_appid, o.precio_oferta ASC, o.oferta_rating DESC NULLS LAST
),
tiendas AS (
    SELECT
        steam_appid,
        ',' || string_agg(DISTINCT tienda::text, ',') || ',' AS tienda_ids
    FROM oferta
    WHERE tienda IS NOT NULL
    GROUP BY steam_appid
)
SELECT
    c.steam_appid,
    c.titulo,
    c.precio_oferta,
    c.ahorro,
    c.oferta_rating,
    c.recent,
    c.reviews,
    c.imagen,
    t.tienda_ids
FROM cheapest c
         LEFT JOIN tiendas t USING (steam_appid);

-- Índice único indispensable para refresco concurrente
CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_ofertas_unicas_appid
    ON mv_ofertas_unicas (steam_appid);

COMMIT;
