BEGIN;


CREATE TABLE IF NOT EXISTS captura
(
    id_captura bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    imagen text COLLATE pg_catalog."default",
    miniatura text COLLATE pg_catalog."default",
    videojuego bigint,
    CONSTRAINT captura_pkey PRIMARY KEY (id_captura),
    CONSTRAINT ukewrc1ycqytihkpaw16ilojr7c UNIQUE (imagen)
);

CREATE TABLE IF NOT EXISTS genero
(
    id_genre bigint NOT NULL,
    descripcion character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT genero_pkey PRIMARY KEY (id_genre)
);

CREATE TABLE IF NOT EXISTS genero_videojuego
(
    id_videojuego bigint NOT NULL,
    id_genre bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS movie
(
    id_movie bigint NOT NULL,
    miniatura text COLLATE pg_catalog."default",
    titulo text COLLATE pg_catalog."default",
    video text COLLATE pg_catalog."default",
    videojuego bigint,
    CONSTRAINT movie_pkey PRIMARY KEY (id_movie)
);

CREATE TABLE IF NOT EXISTS oferta
(
    id_oferta character varying(255) COLLATE pg_catalog."default" NOT NULL,
    ahorro double precision NOT NULL,
    inicio_oferta timestamp(6) without time zone,
    oferta_rating double precision NOT NULL,
    precio_oferta double precision NOT NULL,
    precio_original double precision NOT NULL,
    steam_appid bigint NOT NULL,
    steam_rating integer NOT NULL,
    thumb text COLLATE pg_catalog."default",
    titulo character varying(255) COLLATE pg_catalog."default",
    url_compra text COLLATE pg_catalog."default",
    url_imagen text COLLATE pg_catalog."default",
    tienda bigint,
    videojuego bigint,
    CONSTRAINT oferta_pkey PRIMARY KEY (id_oferta)
);

CREATE TABLE IF NOT EXISTS tienda
(
    id_tienda bigint NOT NULL,
    banner text COLLATE pg_catalog."default",
    icon text COLLATE pg_catalog."default",
    logo text COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT tienda_pkey PRIMARY KEY (id_tienda)
);

CREATE TABLE IF NOT EXISTS videojuego
(
    id_videojuego bigint NOT NULL,
    acerca_de text COLLATE pg_catalog."default",
    desarolladores character varying(255) COLLATE pg_catalog."default",
    descripcion text COLLATE pg_catalog."default",
    descripcion_corta text COLLATE pg_catalog."default",
    distribuidora character varying(255) COLLATE pg_catalog."default",
    fecha_lanzamiento date,
    imagen_url text COLLATE pg_catalog."default",
    imagen_url_resolucion_baja text COLLATE pg_catalog."default",
    nombre character varying(255) COLLATE pg_catalog."default",
    steam_rating_percent integer NOT NULL,
    steam_rating_text character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT videojuego_pkey PRIMARY KEY (id_videojuego)
);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_ofertas_unicas AS
SELECT DISTINCT ON (o.steam_appid)
	o.steam_appid,
	o.titulo,
	o.precio_oferta,
	o.ahorro,
	o.oferta_rating,
	o.inicio_oferta AS recent,
	o.steam_rating AS reviews,
	o.thumb AS imagen
FROM oferta o ORDER BY
	o.steam_appid,
	o.precio_oferta ASC,
	o.oferta_rating DESC;


CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_ofertas_unicas_appid
ON mv_ofertas_unicas (steam_appid);


ALTER TABLE IF EXISTS captura
    ADD CONSTRAINT fk1yt0pd005mtvabke004s91v6k FOREIGN KEY (videojuego)
    REFERENCES videojuego (id_videojuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS genero_videojuego
    ADD CONSTRAINT fkc519kmwd5uy6u8atr37kklu58 FOREIGN KEY (id_genre)
    REFERENCES genero (id_genre) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS genero_videojuego
    ADD CONSTRAINT fkphd8wkrab0931e80a18a60kod FOREIGN KEY (id_videojuego)
    REFERENCES videojuego (id_videojuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS movie
    ADD CONSTRAINT fkmdeiydu2c078pm8qqlsit7jj6 FOREIGN KEY (videojuego)
    REFERENCES videojuego (id_videojuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS oferta
    ADD CONSTRAINT fk1svoog8247ergtlg3lann9rx0 FOREIGN KEY (tienda)
    REFERENCES tienda (id_tienda) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS oferta
    ADD CONSTRAINT fkdxjl92e374vjjhf04a0s8jq2j FOREIGN KEY (videojuego)
    REFERENCES videojuego (id_videojuego) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;