spring.application.name=Recetas

spring.datasource.url=jdbc:postgresql://localhost:5432/Pokemon
spring.datasource.username=postgres
spring.datasource.password=Reach432K
spring.jpa.hibernate.ddl-auto=update